- Model/GooglePay/Helper/QuoteUpdater.php
- Model/Paypal/Helper/QuoteUpdater.php
Currently there is no simple way for developers to add custom attributes sent via PayPal / Google Pay to Magento unless we create plugins or preferences. Adding events onto the quote updater class will allow developers to hook onto this event via observables.
See: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html
`braintree_paypal_update_quote_before` Fires before the quote is updated with the PayPal response
`braintree_paypal_update_quote_after` Fires after the quote is updated with the PayPal response
`braintree_googlepay_update_quote_before` Fires before the quote is updated with the Google Pay response
`braintree_googlepay_update_quote_after` Fires after the quote is updated with the Google Pay response
> Feature: Added quote updater events for PayPal and Google Pay

- view/frontend/web/js/applepay/api.js
Ensure shipping method code is a string
> FD-9322 Apple Pay Shipping Method

- Setup/UpgradeData.php
- composer.json
- etc/adminhtml/system.xml
- etc/module.xml
Hotfix to solve the issue of incorrectly saved config value for LPM allowed methods.
> LPM allowed methods hotfix

- Gateway/Response/CardDetailsHandler.php
- etc/config.xml
See https://github.com/genecommerce/module-braintree-magento2/pull/54
This is for the v4.x.x branch
> Add `uk-maestro` to CC Types to fully support Maestro cards.

- Gateway/Request/Level23ProcessingDataBuilder.php
Update Level23ProcessingDataBuilder.php to fix line item discount
> Update Level23ProcessingDataBuilder.php to fix line item discount

- etc/config.xml
- etc/payment.xml
[PBSD-46/BUNDLE-2686] Displayed Braintree payment methods in a single group(Braintree) in the payment method drop-down of Cart Price Rules.
> [PBSD-46/BUNDLE-2686] Displayed Braintree payment methods under single group(Braintree) in cart price rules.

- Block/Paypal/Button.php
- Block/Paypal/ProductPage.php
- Controller/Paypal/Review.php
- Gateway/Config/PayPalPayLater/Config.php
- Gateway/Request/Level23ProcessingDataBuilder.php
- Gateway/Response/PayPal/VaultDetailsHandler.php
- Model/Ui/PayPal/ConfigProvider.php
- composer.json
- etc/adminhtml/system.xml
- etc/config.xml
- etc/di.xml
- etc/module.xml
- etc/payment.xml
- view/base/requirejs-config.js
- view/frontend/layout/checkout_index_index.xml
- view/frontend/templates/paypal/button.phtml
- view/frontend/templates/paypal/product_page.phtml
- view/frontend/web/js/paypal/button.js
- view/frontend/web/js/view/payment/adapter.js
- view/frontend/web/js/view/payment/method-renderer/paypal.js
- view/frontend/web/template/payment/paypal-credit.html
- view/frontend/web/template/payment/paypal.html
* [Feature] PayPal Buy Now Pay Later (BNPL)
* [Bug] Fixed 'validateRequestData()' method must be of the type array error of PayPal Review page
* [Enhancement] Displayed Braintree payment methods under a single group(Braintree) in cart price rules.
> v4.0.5 - PayPal BNPL

- Gateway/Data/Order/OrderAdapter.php
- Gateway/Request/AddressDataBuilder.php
Implemented fix for the address detail mentioned in the 3rd line of the street field was not getting passed to Braintree issue.
> [PBSD-91] Fixed 3rd line of street field not being sent to Braintree issue

- view/frontend/web/js/view/payment/3d-secure.js
Reverts genecommerce/module-braintree-magento2#91
> Revert "[PBSD-30] Fixed 3D secure card verification error of special characters for Name fields"

- view/frontend/web/js/view/payment/3d-secure.js
- view/frontend/web/js/view/payment/method-renderer/paypal.js
Applied fix for the wrong amount being sent to PayPal when promotion code applied from checkout page and Gateway responses error for 3D-secure cards when the amount is having more than 2 decimal points.
> [PBSD-35] Fixed Wrong amount being sent to PayPal when promotion code applied from checkout page

- Block/Adminhtml/Form/Field/Validation.php
- Controller/Adminhtml/Configuration/Validate.php
- Gateway/Config/Config.php
- Model/Adapter/BraintreeAdapter.php
- etc/adminhtml/system.xml
- etc/config.xml
- view/adminhtml/web/js/system.js
Both production and sandbox credentials can be stored separately.
> [PBSD-5] Allow production and sandbox credentials to be stored

- Console/VaultMigrate.php
- Model/Adminhtml/Source/CcType.php
- README.md
- Test/Unit/Block/FormTest.php
- etc/config.xml
Reverts genecommerce/module-braintree-magento2#92
> Revert "[PBSD-7] Removed China Union Pay(CUP) from list of allowed cards"

- Gateway/Request/Level23ProcessingDataBuilder.php
Fixed issue of a product name is not getting passed to the request when it is having special characters or other language characters.
> [PBSD-102] Fixed issue of product name when it is having special characters or other language characters.

- Block/Paypal/Button.php
- Model/Paypal/Helper/QuoteUpdater.php
- Model/Ui/PayPal/ConfigProvider.php
- view/frontend/templates/paypal/button.phtml
- view/frontend/templates/paypal/product_page.phtml
- view/frontend/web/js/paypal/button.js
- view/frontend/web/js/view/payment/method-renderer/paypal.js
The billing address from PayPal was not getting populated in the Magento order even after selecting the **Require Customer's Billing Address** configuration option value as **YES** from the admin panel.
> [PBSD-32] Fixed Billing Address from PayPal not getting populated issue.

- Gateway/Data/Order/OrderAdapter.php
- Gateway/Request/Level23ProcessingDataBuilder.php
- Gateway/Request/ThreeDSecureDataBuilder.php
- Gateway/Request/VaultDataBuilder.php
- Model/Multishipping/PlaceOrder.php
- composer.json
- etc/di.xml
- etc/payment.xml
- view/frontend/layout/multishipping_checkout_billing.xml
- view/frontend/templates/multishipping/form.phtml
- view/frontend/templates/multishipping/form_paypal.phtml
- view/frontend/web/js/view/payment/method-renderer/multishipping/hosted-fields.js
- view/frontend/web/js/view/payment/method-renderer/multishipping/paypal.js
- view/frontend/web/template/payment/multishipping/form.html
- view/frontend/web/template/payment/multishipping/paypal.html
* Implemented multi-shipping functionality
* Fixed other multi-shipping issues
> [PBSD-3] Implemented Multi-shipping functionality

- view/frontend/web/js/view/payment/braintree.js
Fixed LPMs (Local Payment Methods) are not working issue.
> [PBSD-120] Fixed Local Payment Methods are not working issue

- braintree_php/lib/Braintree/Digest.php
Fixed PHP-7.4 compatibility issue
> Fixed 'Array and string offset access syntax with curly braces is deprecated' issue

- Gateway/Command/GatewayCommand.php
Added ability for message translation
> Add correct translation for gateway response

- Model/Paypal/CreditApi.php
This returns a bool not an int
> Correct bool check

- Gateway/Data/AddressAdapterInterface.php
- Gateway/Data/Order/AddressAdapter.php
- Gateway/Data/Order/OrderAdapter.php
- Gateway/Request/AddressDataBuilder.php
- etc/di.xml
Extends Magento's AddressAdapterInterface to avoid erros on other payment methods.
Added method 'getStreet' to AddressAdapter to get all addresses
> Extends Magento's AddressAdapterInterface

- view/frontend/web/js/view/payment/adapter.js
Injecting hosted fields styles via separate function so they can be easily modified by mixin
> Hosted fields style basic function

- Gateway/Config/Config.php
- Model/Ui/ConfigProvider.php
- Test/Unit/Gateway/Request/ThreeDSecureDataBuilderTest.php
- Test/Unit/Model/Ui/ConfigProviderTest.php
- etc/adminhtml/system.xml
- view/frontend/web/js/view/payment/3d-secure.js
Reverts genecommerce/module-braintree-magento2#192
> Revert "Implemented 3DS Challenge Requested for always if admin configuration field is set to YES"

- view/frontend/web/template/payment/form.html
- view/frontend/web/template/payment/paypal.html
This PR is a fix for the tooltip text spelling.
> Fixed tooltip text spelling

- Plugin/AddAgreementsToMinicartConfig.php
- Plugin/AddFlagForVirtualProducts.php
- etc/di.xml
- view/frontend/web/js/applepay/api.js
- view/frontend/web/js/applepay/button.js
- Fixed Apple Pay for virtual, gift cards and downloadable products
- Fixed Apple Pay checkout agreement issues
> Fixed Apple Pay for virtual products

- Block/System/Config/Form/Field/RequiresStatus.php
- Controller/Webhook/FraudProtection.php
- Model/Config/Source/FraudProtectionUrl.php
- Model/Webhook/Config.php
- etc/adminhtml/system.xml
- etc/config.xml
- view/frontend/web/js/view/payment/method-renderer/ach.js
- Implemented Webhooks for Fraud Protection and ACH payments
- Fixed ACH payment loading issue on checkout page
> Implemented Webhooks for Fraud Protection and ACH payments

- Ui/Component/Report/DataProvider/FilterPool.php
- Ui/Component/Report/Listing/Column/PaymentType.php
- etc/di.xml
- Fixed Braintree Settlement Report - Call to undefined error
- Removed unsupported Payment Types and updated with correct one.
> Fixed Braintree Settlement Report page issue

- Gateway/Config/Config.php
- Model/Ui/ConfigProvider.php
- Test/Unit/Gateway/Request/ThreeDSecureDataBuilderTest.php
- etc/adminhtml/system.xml
- view/frontend/web/js/view/payment/3d-secure.js
- Implemented always request the 3DS challenge to the bank.
- Added admin configuration called **Always request 3DS** as **Yes/No** field to handle it
> Implemented 3DS always challengeRequested feature

- Block/Adminhtml/System/Config/Preview.php
- Controller/GooglePay/Review.php
- Model/GooglePay/Helper/QuoteUpdater.php
- Fixed syntax, unexpected 'QuoteUpdater' error
> Fixed compiler errors
