- Block/Paypal/Button.php
- Gateway/Config/PayPal/Config.php
- Model/Adminhtml/Source/DisabledFundingOptions.php
- Model/Config/Source/Color.php
- Model/Config/Source/Layout.php
- Model/Config/Source/Size.php
- Model/Ui/ConfigProvider.php
- Model/Ui/PayPal/ConfigProvider.php
- etc/adminhtml/system.xml
- etc/config.xml
- view/frontend/templates/paypal/button.phtml
- view/frontend/web/js/paypal/button.js
- view/frontend/web/js/view/payment/adapter.js
- view/frontend/web/js/view/payment/braintree.js
- view/frontend/web/js/view/payment/method-renderer/paypal.js
- view/frontend/web/template/payment/paypal-credit.html
- view/frontend/web/template/payment/paypal.html
1. Updated the customer facing side to implement the smart button code inline with Magento 1 (following the same recommended guidelines)
2. Updated the Magento 2 admin to expose the same settings to change the "Shape, Size, Colour & Layout" for the Cart, mini-cart and checkout pages.
3. Updated the Magento 2 admin to allow the user to disable certain payment funding options (the card icons and the German ELV method)
4. Amended the Magento 2 frontend to take into account all the new settings
> Smart Payment Update REF #87f593ef4227a21e37d91a04e79e00c0ad9bcd47

- Gateway/Config/PayPalCredit/Config.php
Found issue where running the PayPal Credit Price cron in Braintree Production Environment would always return the PayPal sandbox url in https://github.com/genecommerce/module-braintree-magento2/blob/master/Gateway/Config/PayPalCredit/Config.php#L164
* Enable Production mode in Braintree settings
1. Run the Braintree PayPal Credit Cron in Braintree Production mode
PayPal Credit prices get updated and cron finishes with no exceptions
`[Exception]
Unable to retrieve PayPal API token. Error returned with request to https://api.sandbox.paypal.com/v1/oauth2/token. Error: invalid_client`
The original code
`return (bool) $this->getConfigValue('payment/braintree/environment') == 'sandbox';`
PHP would run the typecast to the string first for example 
`(bool) …
> Fixed issue with PayPal Credit sandbox check

- view/frontend/web/js/paypal/button.js
Without this change all the PayPal transactions are not returning the second address line.
> Add second address line on PayPal button componenet

- Block/ApplePay/Shortcut/Button.php
When there is no quote id, the getQuoteId throws an exception. It is suppressed in developer mode, but stops the rest of the request from executing. This change will allow this function to return gracefully.
> prevent exception when no cart on the session and return gracefully

- Api/AuthInterface.php
- Api/CreditPriceRepositoryInterface.php
- Api/Data/CreditPriceDataInterface.php
- Api/Data/TransactionDetailDataInterface.php
- Model/ResourceModel/CreditPriceRepository.php
Fixes Magento 2 docblock coding standards as required from: https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html
> It is encouraged to use the short form of the name to encourage readability and consistency with the type hint. **The only exception is in the Service/DTO classes due to tooling requirements**.
> Fix broken Magento's Swagger due to Magento2 coding standards

- view/frontend/web/js/view/payment/method-renderer/hosted-fields.js
Steps to replicate:
* Clean Magento 2 install
* Install Gene Braintree module v3.2.1
* Set 'CVV Verification' to 'No' in Checkout -> Advanced Braintree Settings
* Add product to basket
* Fill out all shipping fields and proceed to billing
* Select credit/debit card and 'place order'
Expected result:
Card information sent to Braintree and order placed.
Actual result:
Nothing happens due to CVV field validation failing
> Fix for CVV validation bug when CVV not enabled in config

- Gateway/Config/PayPalCredit/Config.php
Found issue where if the `Merchant Name` config is set and the store is set to UK/US that PayPal Credit would display in the cart even though the config value for `Enable PayPal through Braintree` and `Enable PayPal Credit through Braintree` are both set to `No`.
This is an issue for developers that use development configuration setup scripts as PayPal credit would show as enabled even though the config value `Enable PayPal Credit through Braintree` is set to `No`
* Config values for `PayPal Credit through Braintree` are setup
1. View a page that contains PayPal Credit e.g the Cart page
If `Enable PayPal Credit through Braintree` is set to `No` then PayPal credit Calculator should not be rendered on the Cart page
PayPal Credit calculator is rendered on the cart page and the `Enable PayPal …
> Add config check for PayPal and PayPal Credit

- Console/VaultMigrate.php
- Model/Adapter/BraintreeAdapter.php
- Test/Unit/Console/VaultMigrateTest.php
- etc/di.xml
This PR introduces the new M1 to M2 Migration console command that allows for the migration of stored cards from a Magento 1 database, into the Magento 2 store.
The console command will connect to the remote M1 database, locate customers that have an assigned Braintree Id and look them up in the Braintree account.
For this reason, the command should be ran with Braintree set to Production mode.
Currently, only basic unit testing is implemented, with the understanding that Integration Tests need to be added.
**Usage**
Run `bin/magento braintree:migrate --host=<host/ip> --dbname=<db name> --username=<db username> --password=<db password>`
NB - `--username` and `--password` can be supplied either as an argument or if not, they will be asked as interactive questions.
> M1 to M2 Migration Console Command

- Gateway/Response/CardDetailsHandler.php
- etc/config.xml
Whilst `maestro` was in the config.xml, some cards return the string `UK Maestro` which gets translated to `uk-maestro` in the `CardDetailsHandler` class.
The result of the missing card type was an undefined index error when `getCreditCardType()` was called.
> Add `uk-maestro` to CC Types to fully support Maestro cards.

- etc/di.xml
When this module is present during an initial Magento install, the following error occurs:
```
484 Installing database schema:
485 In Mysql.php line 110:
486                                                                                
487   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'build_db.eav_ent  
488   ity_type' doesn't exist, query was: SELECT `main_table`.* FROM `eav_entity_  
489   type` AS `main_table`                                                        
490                                                                                
491 In Mysql.php line 91:
492                                                                                
493   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'build_db.eav_ent  
494   ity_type' doesn't exist …
```
> Adding proxy to customer repository to fix install error

- Block/System/Config/Form/Fieldset.php
- etc/adminhtml/system.xml
**Enable PayPal Credit through Braintree** field will only be available if Merchant Country is either the **US** or **UK** as it does not support other countries.
> [PBSD-41] PayPal Credit field will only be available if Merchant Country is either US or UK.

- Model/Lpm/Config.php
- etc/adminhtml/system.xml
**Fixed:**
`TypeError: explode() expects parameter 2 to be string, null given in /var/www/source/vendor/paypal/module-braintree-core/Model/Lpm/Config.php:125`
> Fixed LPM - TypeError: explode() expects parameter 2 to be string, null given error (v4.0.6)

- Gateway/Config/Config.php
If you've got multiple stores set up, with different descriptors configured, the call to `getValue` wasn't scoped to the current store when entering an order via the admin control panel.
This fix will scope the descriptor_ values to the current store, like the rest of the configurations in this file.
> resolve descriptors from current store

- Ui/Component/Report/Listing/Column/PaymentType.php
https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#400
Coinbase Payment method has been deprecated and removed from Braintree lib, but not removed from the report UI
> Remove Deprecated Coinbase Payment Method from Report

- view/frontend/web/template/credit/calculator.html
PayPal Credit APR has been changed on 1st April 2021 from 19.9% to 21.9% so implemented that change.
> Changed PayPal Credit APR to 21.9% as requested

- view/frontend/web/js/view/payment/method-renderer/paypal.js
If the customer attempts to apply or remove a coupon code before selecting a payment method, an error is thrown for trying to access a property on a null value.
The customer can apply and remove the coupon code successfully without having to first select a payment method.
The aforementioned error is thrown and the checkout loads indefinitely.
1. Create a cart price rule with a coupon code
2. Add products to the cart
3. Proceed through the checkout to the payment step
4. Apply/remove the coupon code _before_ selecting a payment method
> Fix Applying Coupon Without Payment Method Chosen

- Controller/Paypal/Review.php
Problem: Can't add or remove promo codes on the paypal review page /braintree/paypal/review/
Steps: 
- Setup a coupon code based promotion/cart price rule
- Add an item to the cart
- Checkout with Paypal
- On the final review page /braintree/paypal/review/ attempt to use the coupon
Expected Result: coupon is applied
Actual result: user is returned to the cart page with the error 'Malformed request data. This may be caused by special characters. Please try again'
See #79 for some extra history and context
> Fix add/remove promo code on paypal review page

- Model/ResourceModel/CreditPriceRepository.php
Resolves
```
PHP Fatal error:  Uncaught TypeError: Return value of Magento\Braintree\Model\ResourceModel\CreditPriceRepository::save() must implement interface Magento\Braintree\Api\Data\CreditPriceDataInterface, instance of Magento\Braintree\Model\ResourceModel\CreditPrice returned
```
> return type CreditPriceDataInterface

- Model/Recaptcha/ReCaptchaValidation.php
Fixed - Braintree ReCaptcha was giving an **Incorrect ReCaptcha validation** error while generating an invoice from the admin panel.
> Fixed Braintree ReCaptcha error while generating invoice from the admin panel

- Test/Unit/Gateway/Request/ThreeDSecureDataBuilderTest.php
As stated in ThreeDSecureDataBuilder.php "// 'three_d_secure' was removed in version 4.x.x" the array key is now named "threeDSecure" instead of "three_d_secure". Tests did not pass because of this issue.
> 'three_d_secure' was removed in version 4.x.x

- view/frontend/web/js/applepay/api.js
**Steps to reproduce:**
1. Add some product to the cart
2. On the Cart page, press the "Apple Pay" button
3. Complete the order
4. Go to the order details, see Billing Address
You should have your phone number both in billing and shipment addresses
In the billing address, you see the 0000000000 instead of your phone number
> Fix missing billing telephone with Apple Pay

- view/frontend/web/js/applepay/button.js
- view/frontend/web/js/applepay/implementations/core-checkout/method-renderer/applepay.js
- view/frontend/web/js/googlepay/button.js
- view/frontend/web/js/googlepay/implementations/core-checkout/method-renderer/googlepay.js
https://github.com/genecommerce/module-braintree-magento2 
and in googlepay and applepay
https://github.com/genecommerce/module-braintree-magento2/blob/ea2e577803b16744b44c7e33e3a87bb35c8d747d/view/frontend/web/js/googlepay/button.js#L81 
validation and additionalvalidators are not called before executing call chain on click. button.js relays on context for payment object where validation is available but not additionalValidators.validate() cause this is not revealed by default  . 
default.js > placeOrder() method defines the payment method API in magento2.  before executing placeOrder chain in your own methods you must be sure that all related validators are executed. This is not so in your implementation and the result is that googlepay or applepay is started but validations are only …
> validation and additionalvalidators are not called before executing call chain on click for applepay and googlepay

- view/frontend/web/js/view/payment/method-renderer/paypal.js
adding variable check to getShippingAddress method in case the values are missing due async nature of checkout and unknown module load order. If this issue happens checkout is broken for customers and endless loader is displayed . This can be replicated randomly with default checkout if network is tampered or random 3rd party extensions try to request payment methods on first step (eq: checkout layout is customised by designers) , definitely with any OneStepCheckout  like scenarios when your modules can be exposed when data is not entered on previous steps. 
on some page loads this method gives errors due the fact that quote.shippingAddress() can be  one of the following dependant of init time or module load order: undefined, null, empty array, partial filled array, empty address object, …
> fix: adding variable check to getShippingAddress method

- Block/System/Config/Form/Field/RequiresStatus.php
- etc/adminhtml/system.xml
- view/frontend/web/js/applepay/implementations/core-checkout/method-applepay.js
- view/frontend/web/js/googlepay/implementations/core-checkout/method-googlepay.js
- view/frontend/web/js/view/payment/braintree.js
- Fixed Braintree payment methods are visible at front-end even if credentials haven't added issue
> Added 'requires' dependency for all payment methods

- Gateway/Request/Level23ProcessingDataBuilder.php
- etc/adminhtml/system.xml
- etc/config.xml
- Fixed too many items error
- Added new configuration field called **Send Line Items** as **Yes/No**.
- Line items will only be submitted to the braintreee if it is enabled from the admin panel and Line item is less than 250.
> Fixed Too many line items error
